name: Definition of Done
on:
  pull_request:
    types: [opened, edited]
  

jobs:
  check-dod:
    runs-on: ubuntu-latest
    steps:
      - name: Clone Repo
        uses: actions/checkout@v3
      - name: Check DoD
        uses: platisd/definition-of-done@master
        with:
          dod_yaml: './dod.yaml'
          github_token: ${{ secrets.GITHUB_TOKEN }}